247 - Add space between items in submitters form
uclibs/aaec pull request #265
Opened 2023-10-20 17:53 UTC by Janell-Huyck

Fixes #247 

This PR adds some space between the items of the "Submitters" initial registration form.  It uses Bootstrap's "mt-2" to add some margin to the top of each of the fields.

Image on left is "before".  Image on right is "after".

![Screenshot 2023-10-20 at 1 48 56 PM](https://github.com/uclibs/aaec/assets/57018862/98f6d9fc-1dfe-46de-9150-732600f57f52)

2023-10-20 21:00 UTC, hortongn requested changes
@Janell-Huyck I'd prefer a `mt-3` margin instead of `mt-2`, but I'll yield to @haitzlm's expert opinion.

I don't normally like to add newly discovered issues to an existing PR, but I see we also have the same cramped vertical margins on the publication submission forms.  I think we need a global tweak to those margins.

This is also wonky, but could be a separate PR to fix:
![Screenshot 2023-10-20 at 4 58 00 PM](https://github.com/uclibs/aaec/assets/5639859/e77ba5c6-fda4-42cd-8a22-28ecd807d096)

2023-10-20 21:35 UTC, Janell-Huyck commented
> @Janell-Huyck I'd prefer a `mt-3` margin instead of `mt-2`, but I'll yield to @haitzlm's expert opinion.
> 
> I don't normally like to add newly discovered issues to an existing PR, but I see we also have the same cramped vertical margins on the publication submission forms. I think we need a global tweak to those margins.
> 
> This is also wonky, but could be a separate PR to fix: ![Screenshot 2023-10-20 at 4 58 00 PM](https://user-images.githubusercontent.com/5639859/277050836-e77ba5c6-fda4-42cd-8a22-28ecd807d096.png)

@hortongn This new request is actually addressed in https://github.com/uclibs/aaec/pull/264 so I got ya covered. ;)

2023-10-23 15:39 UTC, Janell-Huyck commented
![Screenshot 2023-10-23 at 11 36 52 AM](https://github.com/uclibs/aaec/assets/57018862/156d175f-c708-4ef1-bf84-d88ff271972f)

2023-10-23 15:58 UTC, haitzlm commented
Frankly, I think it could be spread out a little more.

2023-10-23 16:17 UTC, Janell-Huyck commented
Bear in mind - the view you're seeing is for my larger monitor.  Here's what a 2 looks like on my laptop:
<img width="1512" alt="Screenshot 2023-10-23 at 12 13 32 PM" src="https://github.com/uclibs/aaec/assets/57018862/ba482f79-9c6e-477a-a466-c2adcf6b8c45">

2023-10-23 17:27 UTC, hortongn commented
I think 'mt-4' is the sweet spot for me.

2023-10-23 18:28 UTC, Janell-Huyck commented
Lisa and I talked a while and I was able to see the "main" branch run locally on her machine.  It looks like we used to have two columns, like this:
![MicrosoftTeams-image](https://github.com/uclibs/aaec/assets/57018862/f4783c80-a70f-4404-93f1-6ec1b8eb20bf)
  
I am going to attempt to set us back to this nicer 2-column format, add in spacing of mt-4, and set the text "If 'Other', enter your college..." to italics.

2023-10-23 18:29 UTC, Janell-Huyck commented
The other submission forms were also in 2-columns.

2023-11-16 20:19 UTC, Janell-Huyck commented
Re-doing this to the two-column design in another PR.  Close this one without merging.

2023-11-16 20:19 UTC, closed without merging