WIP - 319 - Restrict Submitters From Accessing Things They Don't Own
uclibs/aaec pull request #323
Opened 2023-12-08 22:39 UTC by Janell-Huyck

Fixes #issuenumber ; refs #issuenumber

Present short summary (50 characters or less)

More detailed description, if necessary. Try to be as descriptive as you can: even if you think that the PR content is obvious, it may not be obvious to others. Include tracebacks if helpful, and be sure to call out any bits of the PR that may be work-in-progress.

Description can have multiple paragraphs and you can use code examples inside:

``` ruby
class PostsController
  def index
    respond_with Post.limit(10)
  end
end
```

Changes proposed in this pull request:
* 
* 
*

2023-12-13 20:33 UTC, Janell-Huyck commented on spec/support/shared_examples/allowed_access.rb
This change allows us to specify the individual publication or submitter profile that we are trying to log in as owners of.  It's calling helper functions located in spec/support/helpers/access_authorization.rb to correctly set up the session variables and request parameters

2023-12-13 20:44 UTC, Janell-Huyck commented on spec/support/helpers/login_helpers_for_unit_tests.rb
helper function used to set the session[:submitter_id] to the id of the resource sent.

2023-12-13 20:46 UTC, Janell-Huyck commented on spec/support/helpers/access_authorization.rb
changes allow us to set the params for a specific resource rather than just a generically created one.  This is needed because of the newly created restrictions where submitters can only change their own work.

2024-01-19 21:18 UTC, hortongn commented
@Janell-Huyck Just to make sure I understand this change correctly, AAEC currently allows any submitter to visit something like http://localhost:3000/artworks/3 and view/edit a publication another submitter added.  The same is true for viewing/editing another person's submitter record.

Your change blocks access if the current submitter is not the person who created those records, correct?  I've verified the bug and verified your change fixes it, but is there anything else this change does that I should verify?

2024-01-19 21:31 UTC, hortongn commented
> @Janell-Huyck Just to make sure I understand this change correctly, AAEC currently allows any submitter to visit something like http://localhost:3000/artworks/3 and view/edit a publication another submitter added. The same is true for viewing/editing another person's submitter record.
> 
> Your change blocks access if the current submitter is not the person who created those records, correct? I've verified the bug and verified your change fixes it, but is there anything else this change does that I should verify?

Oh I see you're also restricting submitter access for certain actions.  This all seems to work correctly, but I'd like to talk through some of the code with you on Monday.  Easier to chat about than having a conversation in comments.

2024-01-29 20:03 UTC, hortongn reviewed
@Janell-Huyck See my refactoring suggestions inline

2024-02-04 18:26 UTC, hortongn requested changes
@Janell-Huyck You call `user_is_admin?` but that method isn't defined.

<img width="814" alt="Screenshot 2024-02-04 at 1 25 36 PM" src="https://github.com/uclibs/aaec/assets/5639859/7e5ac010-45e8-4b96-91ed-c2613dd4e7e1">

2024-02-09 21:09 UTC, Janell-Huyck commented
> @Janell-Huyck You call `user_is_admin?` but that method isn't defined.
It looks like I misplaced a few helper methods I created.  I put them in a spec folder by accident. 🙀 Also looks like my tests weren't complete enough to catch that mistake.  Fixing! 🛠️

2024-02-13 18:40 UTC, Janell-Huyck commented
We had a flaky feature test.  I've added in a line that makes the test wait for a page to load, and I expect this to clear up the problem.

2024-02-15 21:42 UTC, hortongn approved these changes
@Janell-Huyck Looks great.  Thanks for all the work you put into this.  merging

2024-02-15 21:42 UTC, merged