Upgrade to Ruby 3.3.0
uclibs/aaec pull request #336
Opened 2024-01-17 18:18 UTC by Janell-Huyck

Fixes #334 

This PR updates AAEC to Ruby version 3.3.0.  It updates it in CI, the ruby-version file, and the Gemfile.  Because I updated the Gemfile, I went and re-ran "bundle install" to make sure everything was installed properly.  This incidentally updates some of the versions in Gemfile.lock, but this was not a "bundle update" update.

2024-01-30 15:04 UTC, hortongn requested changes
@Janell-Huyck There's also an rbenv line in config/deploy.rb that needs to be changed to 3.3.0.  The README currently mentions ruby 3.2.2 - we should either update the version number or remove it from the README.  Please deploy this branch to libappstest after you make the changes and verify all is well.  Thanks

2024-01-31 22:44 UTC, Janell-Huyck commented
I wasn't able to deploy the branch.  Libappstest doesn't seem to have Ruby version 3.3.0 installed via rbenv.  See Teams thread https://teams.microsoft.com/l/message/19:93d7555d783b4397aa7814cfe8e70c0d@thread.skype/1706740878406?tenantId=f5222e6c-5fc6-48eb-8f03-73db18203b63&groupId=05379e3e-d136-48a1-ba71-81ecaf83cfab&parentMessageId=1706740878406&teamName=UCL%20Application%20Development%20Unit&channelName=aaec&createdTime=1706740878406

2024-02-01 20:15 UTC, Janell-Huyck commented
This will deploy on libappstest with the following steps:
1) ssh apache@libappstest.libraries.uc.edu (password in config vault)
2) set the ruby local version to 3.3.0 with `rbenv local 3.3.0`, and then exit ssh
3) `cap qa deploy` from the command line outside of the server

To deploy for production in libapps, we will need to install Ruby version 3.3.0 with the following steps:
1) ssh into libapps
2) update the dependency ruby-build with `git -C /home/apache/.rbenv/plugins/ruby-build pull`
3) install Ruby 3.3.0 with `RUBY_CONFIGURE_OPTS="--disable-dtrace" rbenv install 3.3.0`.  (Note dtrace needs to be disabled since we don't have it installed and don't want it.)
4) set the ruby local version to 3.3.0 with `rbenv local 3.3.0` and then exit ssh
5) `cap production deploy` from the command line outside the server

2024-02-01 21:24 UTC, hortongn approved these changes

2024-02-01 21:24 UTC, merged